// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI (migrate/db push/introspect) cần kết nối session-mode (port 5432).
    // Pooler pgbouncer (port 6543) không hỗ trợ đầy đủ lệnh DDL của migration.
    // Runtime query dùng DATABASE_URL (pooler) qua adapter trong src/lib/db.ts.
    url: process.env["DIRECT_URL"],
  },
});
